"""Prueba de migracion

Revision ID: 5dfdd1781cf6
Revises: 47b7e6b9c5ba
Create Date: 2020-10-13 19:28:59.057094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dfdd1781cf6'
down_revision = '47b7e6b9c5ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otro_campo', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otro_campo')
    # ### end Alembic commands ###
