"""Se cambio el nombre del atributo "view_protocol" por "has_view_protocol" en el modelo de "HelpCenter"

Revision ID: c527ddd9954a
Revises: c1bda1433a5c
Create Date: 2020-11-01 10:35:00.266912

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c527ddd9954a'
down_revision = 'c1bda1433a5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('help_center', sa.Column('has_view_protocol', sa.Boolean(), nullable=False))
    op.drop_column('help_center', 'view_protocol')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('help_center', sa.Column('view_protocol', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('help_center', 'has_view_protocol')
    # ### end Alembic commands ###
